### ISSUE TITLE
Does it work with sqlite?

### ISSUE THREAD

**Issue by gregorwolf** [jungsap/capWithS4#1]
Hi Thomas,

I've forked your project to https://github.com/gregorwolf/capWithS4 and changed the cds.requires to use use sqlite. But after running `cds deploy` and `cds run` the output is:

[cds] - serving CatalogService at /catalog - impl: cat-service.js
[ERROR] Model not yet loaded for service sqlite: db/capWithS4.db

Should it work locally with sqlite?

CU
Gregor

**Comment by jungsap** [comment]
Admittedly I don't have a lot of experience with the local sqlite development approach. I mostly use the Web IDE and HANA.  But I couldn't recreate the error you got.  I downloaded my project and changed the package.json and the .cdsrc.json.  That seems to be the only difference I see between my local project and your repository.  You didn't change the .cdsrc.json. But those are the only two files I changed and then I could deploy and run without error.  
<img width="480" alt="2019-03-29_9-32-15" src="https://user-images.githubusercontent.com/12159356/55236400-37258d00-5206-11e9-810e-209e626a8fd4.png">

Besides the hdbtabledata/csv to load the mock data, there's nothing in this project that should really be HANA specific. Its all pretty neutral CAP stuff. 

I did have to run npm install in your project structure otherwise I got errors because of the reference to @sap\cds\common. But once I ran the npm install, the rest of the CDS commands ran fine as in the above screenshot.

**Comment by gregorwolf** [comment]
Hi Thomas,

I did the following steps:

Added:
```
  "devDependencies": {
    "sqlite3": "^4.0.6"
  }
```
to srv/package.json

and replaced the CDS section with:

```
  "cds": {
    "requires": {
      "db": {
        "kind": "sqlite",
        "model": "gen/csn.json",
        "credentials": {
          "database": "../db/test.db"
        }
      }
    }
  }
```
Then just change to the srv folder and execute:
```
npm install
```
It downloads all the dependencies and builds the project and with
```
npm start
```
it get's served.
